### PR TITLE
docs: rewrite README

### PR DESCRIPTION
**Pull request by Judge40**
Rewrite the README to
 - Better describe the purpose of the project
 - Detail how to run, build and test the project
 - Include more useful badges for at-a-glance info

TIS21-3142
TIS21-3147

### CODE REVIEW

**Review by EdwardBarclay — APPROVED** [review]

**Comment by ReubenRobertsHEE** [comment]
This looks pretty good: a major improvement on what was there before! 😀  

One thing I was wondering, is it worth mentioning the context of the component within the larger app? For example, that its API is used by tis-trainee-sync to populate the reference mongo database with TIS reference data, or that its API is used by tis-trainee-ui to offer selection options when completing the formRs? I agree this is probably not strictly it's concern, but for someone trying to understand how TSS fits together architecturally, it might be very useful.

I ask also because I'm wondering how much of this sort of thing to add when writing up tis-trainee-sync!

**Comment by Judge40** [comment]
> One thing I was wondering, is it worth mentioning the context of the component within the larger app? For example, that its API is used by tis-trainee-sync to populate the reference mongo database with TIS reference data, or that its API is used by tis-trainee-ui to offer selection options when completing the formRs? I agree this is probably not strictly it's concern, but for someone trying to understand how TSS fits together architecturally, it might be very useful.
> 
> I ask also because I'm wondering how much of this sort of thing to add when writing up tis-trainee-sync!

In my opinion that info fits better elsewhere, the handbook most likely.
While we built this service with a specific use in mind, in theory it could be used anywhere requiring this same data. In the spirit of a microservice having that single job, I feel we should only be concerned with describing its functionality in isolatio. Leaving it up to a higher level to explain its place in whatever solution it is integrated in to.

**Comment by Judge40** [comment]
> I ask also because I'm wondering how much of this sort of thing to add when writing up tis-trainee-sync!

`tis-trainee-sync` is a little hard because it does make some direct calls to other services, so we can't avoid mentioning them.
In hindsight, those calls should probably have been a message publish to a queue that could be picked up by anything. Which would have allowed us to stick to "these are the input queues, these are the output queues, we don't care where its comes from or ends up"

**Comment by ReubenRobertsHEE** [comment]
Yeah, that all makes sense 👍 . I guess there's a higher-level explanation of TSS architecture here: https://github.com/Health-Education-England/dev-handbook/blob/main/tis-self-service/overview.md

**Review by DorisWongNHS — APPROVED** [review]

**Pull request merged**
